version: 2

sources:
  - name: raw_assets
    schema: raw
    tables:
      - name: raw_storage_providers_daily_power
        meta:
          dagster:
            asset_key: ["raw_storage_providers_daily_power"]
      - name: raw_datacapstats_verified_clients
        meta:
          dagster:
            asset_key: ["raw_datacapstats_verified_clients"]
      - name: raw_filecoin_state_market_deals
        meta:
          dagster:
            asset_key: ["raw_filecoin_state_market_deals"]
      - name: raw_storage_providers_location_provider_quest
        meta:
          dagster:
            asset_key: ["raw_storage_providers_location_provider_quest"]
      - name: raw_storage_providers_filrep_reputation
        meta:
          dagster:
            asset_key: ["raw_storage_providers_filrep_reputation"]
      - name: raw_verified_registry_verifiers
        meta:
          dagster:
            asset_key: ["raw_verified_registry_verifiers"]
      - name: raw_datacapstats_verifiers
        meta:
          dagster:
            asset_key: ["raw_datacapstats_verifiers"]
      - name: raw_storage_providers_token_balances
        meta:
          dagster:
            asset_key: ["raw_storage_providers_token_balances"]
      - name: raw_storage_providers_rewards
        meta:
          dagster:
            asset_key: ["raw_storage_providers_rewards"]
      - name: raw_spark_retrievals_onchain_data
        meta:
          dagster:
            asset_key: ["raw_spark_retrievals_onchain_data"]
      - name: raw_datacap_allocators_registry
        meta:
          dagster:
            asset_key: ["raw_datacap_allocators_registry"]
      - name: raw_storage_providers_energy_name_mapping
        meta:
          dagster:
            asset_key: ["raw_storage_providers_energy_name_mapping"]
      - name: raw_storage_providers_sector_totals
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_totals"]
      - name: raw_storage_providers_sector_terminations
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_terminations"]
      - name: raw_storage_providers_sector_faults
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_faults"]
      - name: raw_storage_providers_sector_recoveries
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_recoveries"]
      - name: raw_storage_providers_sector_expirations
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_expirations"]
      - name: raw_storage_providers_sector_extensions
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_extensions"]
      - name: raw_storage_providers_sector_snaps
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_snaps"]
      - name: raw_storage_providers_sector_durations
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_durations"]
      - name: raw_storage_providers_sector_commits_count
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_commits_count"]
      - name: raw_storage_providers_sector_commits_size
        meta:
          dagster:
            asset_key: ["raw_storage_providers_sector_commits_size"]
      - name: raw_datacap_github_applications
        meta:
          dagster:
            asset_key: ["raw_datacap_github_applications"]
      - name: raw_network_user_address_count
        meta:
          dagster:
            asset_key: ["raw_network_user_address_count"]
      - name: raw_id_addresses
        meta:
          dagster:
            asset_key: ["raw_id_addresses"]
      - name: raw_circulating_supply
        meta:
          dagster:
            asset_key: ["raw_circulating_supply"]
      - name: raw_block_rewards
        meta:
          dagster:
            asset_key: ["raw_block_rewards"]
      - name: raw_network_base_fee
        meta:
          dagster:
            asset_key: ["raw_network_base_fee"]
      - name: raw_storage_providers_deal_count
        meta:
          dagster:
            asset_key: ["raw_storage_providers_deal_count"]
      - name: raw_storage_providers_deal_duration
        meta:
          dagster:
            asset_key: ["raw_storage_providers_deal_duration"]
      - name: raw_storage_providers_deal_revenue
        meta:
          dagster:
            asset_key: ["raw_storage_providers_deal_revenue"]
      - name: raw_gas_daily_usage
        meta:
          dagster:
            asset_key: ["raw_gas_daily_usage"]
      - name: raw_oso_daily_filecoin_collection_events
        meta:
          dagster:
            asset_key: ["raw_oso_daily_filecoin_collection_events"]
      - name: raw_daily_providers_sector_events
        meta:
          dagster:
            asset_key: ["raw_daily_providers_sector_events"]
      - name: raw_daily_direct_data_onboarding
        meta:
          dagster:
            asset_key: ["raw_daily_direct_data_onboarding"]
      - name: raw_filecoin_transactions
        meta:
          dagster:
            asset_key: ["raw_filecoin_transactions"]
      - name: raw_filecoin_storage_providers_information
        meta:
          dagster:
            asset_key: ["raw_filecoin_storage_providers_information"]
      - name: raw_storage_providers_gas_network_fee
        meta:
          dagster:
            asset_key: ["raw_storage_providers_gas_network_fee"]
      - name: raw_storage_providers_gas_commit_fee
        meta:
          dagster:
            asset_key: ["raw_storage_providers_gas_commit_fee"]
      - name: raw_onramp_mappings
        meta:
          dagster:
            asset_key: ["raw_onramp_mappings"]
      - name: raw_fil_price
        meta:
          dagster:
            asset_key: ["raw_fil_price"]
