with source as (
    select
        addressId as client_id,
        aa ->> '$.unnest.id' as allowance_id,
        aa ->> '$.unnest.error' as allowance_error,
        aa ->> '$.unnest.height' as height,
        aa ->> '$.unnest.msgCID' as message_cid,
        aa ->> '$.unnest.retries' as retries,
        aa ->> '$.unnest.allowance' as allowance,
        aa ->> '$.unnest.auditTrail' as audit_trail,
        aa ->> '$.unnest.allowanceTTD' as allowance_ttd,
        aa ->> '$.unnest.isDataPublic' as is_data_public,
        aa ->> '$.unnest.issueCreator' as issue_creator,
        aa ->> '$.unnest.providerList' as provider_list,
        aa ->> '$.unnest.usedAllowance' as used_allowance,
        aa ->> '$.unnest.isLdnAllowance' as is_ldn_allowance,
        aa ->> '$.unnest.isEFilAllowance' as is_efil_allowance,
        aa ->> '$.unnest.verifierAddressId' as allocator_id,
        aa ->> '$.unnest.isFromAutoverifier' as is_from_autoverifier,
        aa ->> '$.unnest.retrievalFrequency' as retrieval_frequency,
        aa ->> '$.unnest.searchedByProposal' as searched_by_proposal,
        aa ->> '$.unnest.issueCreateTimestamp' as issue_create_timestamp,
        aa ->> '$.unnest.hasRemainingAllowance' as has_remaining_allowance,
        aa ->> '$.unnest.createMessageTimestamp' as create_message_timestamp,
        aa ->> '$.unnest.addressId' as allowance_address_id,
        aa ->> '$.unnest.dcSource' as dc_source,
    from {{ source("raw_assets", "raw_datacapstats_verified_clients") }}, unnest(allowanceArray) as aa
),

github_applications_allocations as (
    select
        ar ->> '$.unnest.Signers[0].Message CID' as message_cid,
        ar ->> '$.unnest.Signers[0].Github Username' as allocation_request_github_username,
        ar ->> '$.unnest.Signers[0].Signing Address' as allocation_request_signing_address,
        ar ->> '$.unnest.ID' as allocation_request_id,
        ar ->> '$.unnest.Request Type' as allocation_request_type,
        ar ->> '$.unnest.Created At' as allocation_request_created_at,
        ar ->> '$.unnest.Updated At' as allocation_request_updated_at,
        ar ->> '$.unnest.Active' as allocation_request_is_active,
        ar ->> '$.unnest.Allocation Amount' as allocation_request_amount,
    from raw.raw_datacap_github_applications, unnest(allocation_requests) as ar
    where message_cid is not null
)

select
    allowance_id::numeric as allowance_id,
    client_id,
    allowance_error,
    height::numeric as height,
    to_timestamp(height::numeric * 30 + 1598306400)::timestamp as height_at,
    s.message_cid,
    retries,
    allowance::bigint as allowance_bytes,
    allowance::bigint / power(1024, 4) as allowance_tibs,
    sum(allowance_bytes) over (partition by client_id order by height rows between unbounded preceding and current row) as client_total_received_datacap_bytes,
    client_total_received_datacap_bytes / power(1024, 4) as client_total_received_datacap_tibs,
    audit_trail,
    try_cast(allowance_ttd as numeric) as allowance_ttd,
    if(is_data_public = 'yes', true, false) as is_data_public,
    issue_creator,
    provider_list,
    used_allowance::bigint as used_allowance,
    is_ldn_allowance,
    is_efil_allowance,
    allocator_id,
    allowance_address_id,
    dc_source,
    is_from_autoverifier,
    retrieval_frequency,
    searched_by_proposal,
    to_timestamp(try_cast(issue_create_timestamp as numeric)) as issue_created_at,
    has_remaining_allowance,
    to_timestamp(try_cast(create_message_timestamp as numeric)) as messaged_created_at,
    gaa.allocation_request_github_username,
    gaa.allocation_request_signing_address,
    gaa.allocation_request_id,
    gaa.allocation_request_type,
    gaa.allocation_request_created_at,
    gaa.allocation_request_updated_at,
    gaa.allocation_request_is_active,
    gaa.allocation_request_amount
from source as s
left join github_applications_allocations as gaa on s.message_cid = gaa.message_cid
order by height desc
