name: Legacy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  legacy:
    name: Legacy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: legacy
    env:
      SPACESCOPE_TOKEN: ${{ secrets.SPACESCOPE_TOKEN }}
      DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      motherduck_token: ${{ secrets.motherduck_token }}
      DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ENCODED_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.ENCODED_GOOGLE_APPLICATION_CREDENTIALS }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      OSO_API_KEY: ${{ secrets.OSO_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Show Python version
        run: uv run python -V

      - name: Run
        run: make run-ci
