name: Filecoin Pulse

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 20 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pulse:
    name: Filecoin Pulse
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=8192"
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: pulse/package-lock.json

      - name: Install dependencies
        working-directory: pulse
        run: npm ci

      - name: Run sources
        working-directory: pulse
        run: npm run sources

      - name: Build
        working-directory: pulse
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
          command: pages deploy pulse/build --project-name=filecoinpulse --branch=dev
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
