name: Website

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'web/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        run: npm ci --prefix web

      - name: Build
        run: npm run build --prefix web

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fbe814d4a37d3d3d7fcfeec0ab929ff6
          command: pages deploy web/dist --project-name=filecoindataportal --branch=main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
